package com.techfun.database.entity;

import java.io.Serializable;

public class Employees implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.employee_id
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.password
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.email
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.employee_name
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.phone
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.address
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.remark
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employees
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.employee_id
     *
     * @return the value of employees.employee_id
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.employee_id
     *
     * @param employeeId the value for employees.employee_id
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.password
     *
     * @return the value of employees.password
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.password
     *
     * @param password the value for employees.password
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.email
     *
     * @return the value of employees.email
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.email
     *
     * @param email the value for employees.email
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.employee_name
     *
     * @return the value of employees.employee_name
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.employee_name
     *
     * @param employeeName the value for employees.employee_name
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.phone
     *
     * @return the value of employees.phone
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.phone
     *
     * @param phone the value for employees.phone
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.address
     *
     * @return the value of employees.address
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.address
     *
     * @param address the value for employees.address
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.remark
     *
     * @return the value of employees.remark
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.remark
     *
     * @param remark the value for employees.remark
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Fri Sep 22 13:27:30 MMT 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", employeeId=").append(employeeId);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", employeeName=").append(employeeName);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}